# Generated by Django 5.1.4 on 2025-06-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=200)),
                ("branch_address", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("principal", "principal"),
                            ("vice principal", "vice principal"),
                            ("teacher", "teacher"),
                            ("incharge", "incharge"),
                            ("peon", "peon"),
                            ("guard", "guard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=250, null=True)),
                ("salary", models.IntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="schools.school"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("play group", "play group"),
                            ("nursery", "nursery"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fee", models.IntegerField()),
                ("contact", models.CharField(max_length=11)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="schools.school"
                    ),
                ),
            ],
        ),
    ]
